{% set name = "clease" %}
{% set version = "0.11.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6c5921a2fce8b59fba0f96d42cf831e48199a77424b030cf99d95f4739b8259

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - clease=clease.cli.main:clease_cli
  # Limit to python 3.7 or newer
  # and require cython (skip PyPy)
  skip: true  # [py<37 or python_impl != 'cpython']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - pip
    - attrs
    - cython
    - ase >=3.20, <3.23
    - matplotlib-base
    - spglib
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    - typing_extensions
    - scipy
    - deprecated
    - click >=8.0.0
    - packaging
    - threadpoolctl

test:
  imports:
    - clease
  commands:
    - pip check

about:
  home: https://clease.readthedocs.io/
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.md
  summary: CLuster Expansion in Atomic Simulation Environment

  description: |
    CLuster Expansion in Atomic Simulation Environment
  doc_url: https://clease.readthedocs.io/
  dev_url: https://gitlab.com/computationalmaterials/clease

extra:
  recipe-maintainers:
    - jan-janssen
    - atygesen
